#include "libft.h"

const unsigned char g_lup[1 + CTYPE_NUM_CHARS] = {
	0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, FT_S, FT_S, FT_S, FT_S, FT_S, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	FT_P | FT_S, FT_P, FT_P, FT_P,
	FT_P, FT_P, FT_P, FT_P,
	FT_P, FT_P, FT_P, FT_P,
	FT_P, FT_P, FT_P, FT_P,
	FT_D | FT_P, FT_D | FT_P, FT_D | FT_P, FT_D | FT_P,
	FT_D | FT_P, FT_D | FT_P, FT_D | FT_P, FT_D | FT_P,
	FT_D | FT_P, FT_D | FT_P, FT_P, FT_P,
	FT_P, FT_P, FT_P, FT_P,
	FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_P,
	FT_P, FT_P, FT_P, FT_P,
	FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_A | FT_P,
	FT_A | FT_P, FT_A | FT_P, FT_A | FT_P, FT_P,
	FT_P, FT_P, FT_P, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};